apiVersion: v1
kind: Service
metadata:
  name: todo-service
  labels:
    name: todo-service
    app: todo-app
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 3000
  selector:
    name: todo-pod
    app: todo-app