# https://www.cloudytuts.com/guides/kubernetes/how-to-deploy-mongodb-on-kubernetes/
# echo -n 'my-super-secret-password' | base64
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
data:
  MONGO_INITDB_ROOT_PASSWORD: bXktc3VwZXItc2VjcmV0LXBhc3N3b3Jk
stringData:
  MONGO_INITDB_ROOT_USERNAME: myroot