apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: todo-app
spec:
  clusterIP: None
  selector:
    app: todo-app

# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb
# spec:
#   selector:
#     app: todo-app
#   ports:
#   - protocol: TCP
#     port: 27017