- hosts: all
  become: yes
  tasks:
  - name: Install package needed for docker-ce
    yum:
      name:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
      state: present

  - name: Add Docker GPG key.
    rpm_key:
      key: https://download.docker.com/linux/centos/gpg
      state: present

  - name: Add Docker repo
    get_url:
      url: https://download.docker.com/linux/centos/docker-ce.repo
      dest: /etc/yum.repos.d/docer-ce.repo

  # TODO: allowerasing? 
  - name: Install Docker
    yum:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: latest

  - name: start Docker
    service:
      name: docker
      state: started

  - name: disable SELinux
    command: setenforce 0

  - name: disable SELinux on reboot
    selinux:
      state: disabled

  - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

  - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
    sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

  - name: add Kubernetes' YUM repository
    yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

  - name: install kubelet
    yum:
      name: kubelet
      state: present
      update_cache: true

  - name: install kubeadm
    yum:
      name: kubeadm
      state: present

  - name: start kubelet
    service:
      name: kubelet
      enabled: yes
      state: started

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl
        state: present
        allow_downgrade: yes