---
- hosts: tag_Group_master
  vars:
    user: ansible_user
    hashed_password: $1$NRY3GEe1$6KQL5zNNGLcW/s1eMNhnW0
  tasks:
    - name: yum update
      become: yes
      command: yum update

    - name: enable ssh with password
      become: yes
      command: "sed -i'' -e 's/#PasswordAuthentication yes/PasswordAuthentication yes'"

    - name: restart sshd
      become: yes
      command: systemctl restart sshd

    - name: create ansible_user user
      user: name={{ user }} state=present password={{ hashed_password }}

    - name: add ansible_user to sudoers
      lineinfile:
        dest: /etc/sudoers
        state: present
        regexp: '^%ansible_user'
        line: 'ansible_user ALL=(ALL) NOPASSWD:ALL'
        validate: 'visudo -cf %s'